mdsol/mauth-client-ruby

.travis.yml, CHANGELOG.md, README.md, lib/mauth/version.rb, mauth-client.gemspec
Trouble happened while publishing 4.0.0 on rubygems.org and since the same version cannot be re-upload we have to bump the version number.
Add the Travis CI config while we're at it.
@mdsol/team-10
=> bump to 4.0.1, use Travis CI

CHANGELOG.md, lib/mauth/client.rb, lib/mauth/version.rb, spec/mauth_client_spec.rb
Special characters in uri `com:mdsol:study_environments:6975285c-164d-4475-b848-25b0c8852510rqcwyungou&#65;902xcd7c9o` caused MAuth to reject the signed request. This PR adds the octothorpe/pound sign (`#`) to the gsub which already escapes the forward slash.
Specs updated to match.
This request should have been handled properly on the client's side, since # denotes a fragment. However, since the platform does not have a rigorous uri definition, this may occur again.
=> [MCC-286290] Add # to signature escape 

.gitignore, CHANGELOG.md, lib/mauth/proxy.rb, lib/mauth/version.rb, mauth-client.gemspec, spec/proxy_spec.rb
Having talked with @johngluckmdsol offline about https://github.com/mdsol/mauth-client-ruby/pull/11, this PR is inspired by his fix and from his discussion with @cabbott.  It seems like when the proxy was originally created in https://github.com/mdsol/mauth-client/pull/45 that the intent was to forward headers that begin with `HTTP_` but to remove the leading `HTTP_` (but to not forward `HTTP_HOST`).  This PR restores that behavior that was changed in https://github.com/mdsol/mauth-client/pull/106.
@jfeltesse-mdsol
=> Fix forwarding of headers starting with http_ in the proxy

.travis.yml
New versions of the gem should automatically be sent to Rubygems now on tagged commits.
@mdsol/team-10 @johngluckmdsol
=> Adds integration between travis and rubygems

.travis.yml, CHANGELOG.md, Rakefile, gemfiles/ruby_2.1.gemfile, lib/mauth/version.rb, mauth-client.gemspec, spec/mauth_client_spec.rb, spec/spec_helper.rb
Ruby 2.2 [has reached EOL](https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/). Technically this gem is obviously still compatible with earlier versions so it's only about whether we want to support EOL rubies and the version the users of this gem are using.
AFAIK at medidata all ruby projects that are maintained and developed are at least at 2.3.x.
At the same time I cleaned up the dev dependencies:
- updated where applicable
- removed kender because it was not used
- removed uuidtools because securerandom does the job just fine now
I also cleaned up the travis file, the fixes around bundler are not needed anymore.
About the semver, doing a major vs minor bump in this case is subject to interpretation.
I think [this …
=> Drop support for ruby < 2.3.0 and update dev dependencies

.travis.yml
See:
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
@mdsol/team-16
=> [MCC-456036] Remove sudo: false from .travis.yml

CHANGELOG.md, lib/mauth/client.rb, lib/mauth/version.rb, spec/mauth_client_spec.rb
Not having the header may be normal operation for some services, do not use error.
I've not touched other situations like when the header is present but the time is off, this may point to a service with a problem with its clock for instance.
@ejennings-mdsol  @mszenher
=> Uses warning instead of error for logs when the mauth header is missing

CONTRIBUTING.md, Rakefile
@mdsol/team-16 this adds V2 signing to the benchmark rake task.
Adding DNM because this is pointed at the `feature/v2-mauth-protocol`.
=> [MCC-412658] Add V2 to benchmark

spec/support/shared_examples/authenticator_base.rb
@mdsol/team-16  
This PR adds the use of Timecop to two specs that can flicker because of rounding. You can see these spes, which were recently updated to include time offsets of `-300` and `300`, have failed CI on master on two past merge commits (828a6f75dbaa437b602d85c7eba4ce76580ae6aa and f76191e74fe55afa2d049457c2837e4653594272). 
We could also remove the time offsets of +/-300.
=> [MCC-412658] Fix flickering spec

lib/mauth/client/local_authenticator.rb, lib/mauth/client/signer.rb, lib/mauth/request_and_response.rb, spec/client/signer_spec.rb, spec/signable_spec.rb
@mdsol/team-16 
[JIRA](https://jira.mdsol.com/browse/MCC-412658)
This PR updates the mAuth V2 protocol to use the RSA `sign` and `verify` standard methods for digital signature schemes (see docs for these methods [here](http://ruby-doc.org/stdlib-2.6.1/libdoc/openssl/rdoc/OpenSSL/PKey/PKey.html)). This is in response to concerns raised about the current use of the non-standard `private_encrypt` in this issue: https://github.com/mdsol/mauth/issues/59.
=> [MCC-412658] Use RSA sign and RSA verify

exe/mauth-client, lib/mauth/client/authenticator_base.rb, lib/mauth/errors.rb, lib/mauth/rack.rb, spec/middleware_spec.rb, spec/support/shared_examples/authenticator_base.rb
@mdsol/team-16 last small fixes for v5. I noticed the casing was inconsistent in the `MauthNotPresent` error name while i was updating mauth service to use the new client. This is a simple find and replace PR.
=> [MCC-412658] Make casing of error consistent

CHANGELOG.md, lib/mauth/client/local_authenticator.rb, lib/mauth/version.rb, spec/client/local_authenticator_spec.rb
@mdsol/team-16 
@yboyadjan observed that query strings with special characters were not being correctly authenticated when submitted via v2 mAuth authentication tickets. This demonstrated an issue with the way we're doing the special euresource escaping for query strings. 
Eureka client generates query strings using the the method documented [here](https://www.rubydoc.info/gems/addressable/2.3.4/Addressable/URI#query_values=-instance_method) on [this line](https://github.com/mdsol/eureka-client/blob/0af64745dfc3bc99554e28b49d95dbd9900d042c/lib/google/api_client/discovery/method.rb#L175). It encodes all special characters in query param keys and values (including `/` and `#`) but does not encode the `=` and `&` that connect keys and values and k/v pairs. Previously I used the same …
=> [MCC-413109] Fix Euresource escaping of query params

CHANGELOG.md, lib/mauth/request_and_response.rb, lib/mauth/version.rb, spec/signable_spec.rb
The following error is raised when `# frozen_string_literal: true` is in use:
```
FrozenError: can't modify frozen String
/opt/ruby/gems/2.5.0/gems/mauth-client-5.0.1/lib/mauth/request_and_response.rb:77:in `force_encoding'
```
Similar issue found in Sinatra: 
https://github.com/sinatra/sinatra/issues/1478
Simply using the `dup` method.
@mdsol/team-16 @mdsol/team-10
=> Fix to not raise FrozenError when string to sign contains frozen value

spec/client/signer_spec.rb, spec/fixtures/mauth_signature_testing.json
Related to #35, this PR is to add the cross-platform signature value checks to make sure all mauth-clients implement the MAuth specification correctly.
@mdsol/team-16
@mdsol/architecture-enablement
=> Add cross-platform signature value checks

CHANGELOG.md, lib/mauth/client/authenticator_base.rb, lib/mauth/request_and_response.rb, lib/mauth/version.rb, spec/client/local_authenticator_spec.rb, spec/client/remote_authenticator_spec.rb, spec/support/shared_examples/authenticator_base.rb
Updated the authenticator to fall back to V1 when V2 authentication fails, to migrate smoothly when resolving encoded query parameters in V2
~~Will add MCC later 😅~~ 
@mdsol/team-16 @mdsol/team-51 @mdsol/team-10 @mdsol/architecture-enablement
=> [MCC-575217] Fall back to V1 when V2 authentication fails

lib/mauth/request_and_response.rb, spec/signable_spec.rb
@mdsol/team-16 this PR fix sorting of query params. Previously I was sorting using Ruby's `sort` function by key-value strings with the equals sign ([`k=value`, `k2=value`]). This PR fixes the sorting to be first by key then by value by using the `sort` function on an array of tuples: `[['k', 'value'], ['k2', 'value']]`.
The new spec added was 
```
include_examples 'unescape_encode_query_string', 'sorts query with the same base string correctly',
'key2=value2&key=value', 'key=value&key2=value2'
```
the rest of the spec diff is just drying up those specs with shared examples as @jfeltesse-mdsol suggested on #39
=> [MCC-575482] Fix Query Parameter Sorting for Edge Cases

lib/mauth/request_and_response.rb
While attempting to write a new V1 response authenticator from scratch, I discovered that the description in the comments of how the string_to_sign is formed is incorrect. The Ruby code for what actually happens is difficult to follow, but experimentation proves that the signing string is composed of the full response body without any transformations. [See related PR](https://github.com/mdsol/mauth-client-rust/pull/5)
@mdsol/team-16
=> Fix description of the V1 response signing string

CHANGELOG.md, lib/mauth/client/security_token_cacher.rb, lib/mauth/version.rb, spec/client/security_token_cacher_spec.rb
The main change is in 30eb931.
When using mauth-client with ruby 2.7, you will see this warning:
> /home/travis/build/mdsol/mauth-client-ruby/lib/mauth/client/security_token_cacher.rb:27: warning: URI.escape is obsolete
https://travis-ci.org/github/mdsol/mauth-client-ruby/jobs/725788004#L322-L350
`URI.escape` is used only [in SecurityTokenCacher](https://github.com/mdsol/mauth-client-ruby/blob/v6.1.0/lib/mauth/client/security_token_cacher.rb#L27) to encode app_uuid when retrieving public keys from mauth:
```ruby
url_encoded_app_uuid = URI.escape(app_uuid, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))
```
this is encoding characters not in `URI::PATTERN::UNRESERVED`:
```ruby
URI::PATTERN::UNRESERVED
#=> "\\-_.!~*'()a-zA-Z\\d" 
```
`CGI.escape` is encoding a little more characters but it …
=> Replace URI.escape with CGI.escape in SecurityTokenCacher to suppress "URI.escape is obsolete" warning

doc/implementations.md
Both the python and rust clients are public now.
@mdsol/team-16 @mdsol/architecture-enablement @jcarres-mdsol
=> Update MAuth client implementations doc

CHANGELOG.md, lib/mauth/client/security_token_cacher.rb, lib/mauth/version.rb, mauth-client.gemspec
instead of legacy 60s expiry.
- this will allow to leverage existing caching library.
- configure the expiry server side.
- get rid of legacy custom code.
=> use Faraday HTTP Cache to honor server cache control headers

CHANGELOG.md, lib/mauth/client/security_token_cacher.rb, lib/mauth/version.rb, mauth-client.gemspec, spec/client/security_token_cacher_spec.rb, spec/spec_helper.rb
Dropped the internal caching logic (https://github.com/mdsol/mauth-client-ruby/pull/50#discussion_r647050094) to not cache tokens forever.
Added specs to test caching in SecurityTokenCacher.
@mdsol/enablement-ruby
=> Fix SecurityTokenCacher to not cache tokens forever

CHANGELOG.md, lib/mauth/rack.rb, lib/mauth/version.rb, spec/middleware_spec.rb
All in the title. Added specs also.
@mdsol/enablement-ruby
=> Fix MAuth::Rack::Response to not raise FrozenError

lib/mauth/client.rb, spec/spec_helper.rb
=> Remove MAUTH_CONFIG_YML from spec_helper.rb

.github/workflows/ci.yml, .github/workflows/publish.yml, mauth-client.gemspec
All in the title
@ejinotti-mdsol  @ejennings-mdsol
=> feat: Support ruby 3.4
